// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFRrlfJoFQIbl85B8CIf1Iyvy3hprAHio',
    appId: '1:791761849806:ios:4b6e45bf6890f328a32f9f',
    messagingSenderId: '791761849806',
    projectId: 'asfs-929a1',
    storageBucket: 'asfs-929a1.firebasestorage.app',
    iosClientId: '791761849806-6qng80012qmitkhgtog441jvqht47r41.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFRrlfJoFQIbl85B8CIf1Iyvy3hprAHio',
    appId: '1:791761849806:ios:4b6e45bf6890f328a32f9f',
    messagingSenderId: '791761849806',
    projectId: 'asfs-929a1',
    storageBucket: 'asfs-929a1.firebasestorage.app',
    iosClientId: '791761849806-6qng80012qmitkhgtog441jvqht47r41.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC17JLgQKMOoRdjypWjwqPZMuAvHsrB9lk',
    appId: '1:791761849806:web:89493ff3b41f0437a32f9f',
    messagingSenderId: '791761849806',
    projectId: 'asfs-929a1',
    authDomain: 'asfs-929a1.firebaseapp.com',
    storageBucket: 'asfs-929a1.firebasestorage.app',
    measurementId: 'G-QZJ9ZBCTMV',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC17JLgQKMOoRdjypWjwqPZMuAvHsrB9lk',
    appId: '1:791761849806:web:89493ff3b41f0437a32f9f',
    messagingSenderId: '791761849806',
    projectId: 'asfs-929a1',
    authDomain: 'asfs-929a1.firebaseapp.com',
    storageBucket: 'asfs-929a1.firebasestorage.app',
    measurementId: 'G-QZJ9ZBCTMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnweXkHmGP27U1Y6EfZAzI1oxVB0T-kts',
    appId: '1:791761849806:android:b01abfd8e2169d89a32f9f',
    messagingSenderId: '791761849806',
    projectId: 'asfs-929a1',
    storageBucket: 'asfs-929a1.firebasestorage.app',
  );

}